// AUTO-GENERATED by src/export_web_model.py (source: dt_classifier.joblib).
// The real trained model, transpiled to run in the browser. Do not edit by hand.

export const FEATURE_ORDER = ['age', 'vitamin_d_ngml', 'phq9_depression', 'gad7_anxiety', 'mobility_index', 'pain_score', 'sleep_quality_psqi', 'fatigue_score', 'light_sensitivity', 'bmi', 'sun_tolerance', 'caretaker_present'];
export const CLASS_CODES = [0, 1, 2, 3];  // 0=A 1=B 2=C 3=D

function rawScore(input) {
    var var0;
    if (input[11] <= 0.5) {
        if (input[8] <= 4.5) {
            if (input[2] <= 8.5) {
                if (input[7] <= 5.0) {
                    var0 = [0.9488372093023256, 0.0, 0.0, 0.05116279069767442];
                } else {
                    var0 = [0.5, 0.0, 0.0, 0.5];
                }
            } else {
                if (input[10] <= 8.5) {
                    var0 = [0.2087912087912088, 0.0, 0.0, 0.7912087912087912];
                } else {
                    var0 = [0.9333333333333333, 0.0, 0.0, 0.06666666666666667];
                }
            }
        } else {
            if (input[2] <= 5.5) {
                if (input[10] <= 6.5) {
                    var0 = [0.21505376344086022, 0.0, 0.0, 0.7849462365591398];
                } else {
                    var0 = [0.7551020408163265, 0.0, 0.0, 0.24489795918367346];
                }
            } else {
                if (input[1] <= 11.050000190734863) {
                    var0 = [0.4, 0.0, 0.0, 0.6];
                } else {
                    var0 = [0.015748031496062992, 0.0, 0.0, 0.984251968503937];
                }
            }
        }
    } else {
        if (input[8] <= 3.5) {
            if (input[2] <= 12.5) {
                if (input[5] <= 4.5) {
                    var0 = [0.0, 0.9545454545454546, 0.045454545454545456, 0.0];
                } else {
                    var0 = [0.0, 0.14285714285714285, 0.8571428571428571, 0.0];
                }
            } else {
                if (input[9] <= 21.550000190734863) {
                    var0 = [0.0, 1.0, 0.0, 0.0];
                } else {
                    var0 = [0.0, 0.030303030303030304, 0.9696969696969697, 0.0];
                }
            }
        } else {
            if (input[1] <= 19.949999809265137) {
                if (input[8] <= 5.5) {
                    var0 = [0.0, 0.7346938775510204, 0.2653061224489796, 0.0];
                } else {
                    var0 = [0.0, 0.18487394957983194, 0.8151260504201681, 0.0];
                }
            } else {
                if (input[1] <= 54.5) {
                    var0 = [0.0, 0.040268456375838924, 0.959731543624161, 0.0];
                } else {
                    var0 = [0.0, 1.0, 0.0, 0.0];
                }
            }
        }
    }
    return var0;
}

export function scoreGroups(input) { return rawScore(input); }
